#!/bin/sh
set -e

echo "Running lint..."
pnpm lint

echo "Running typecheck..."
pnpm typecheck

echo "Running format..."
STAGED=$(git diff --cached --name-only)
pnpm format
echo "$STAGED" | xargs git add

echo "All checks passed!"
